shamefullyHoist: true
allowBuilds:
  better-sqlite3: true
  workerd: true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  sharp: true
  typeit: true
  lefthook: true
minimumReleaseAgeExclude:
  - lefthook-darwin-arm64@2.1.9
  - lefthook-darwin-x64@2.1.9
  - lefthook-freebsd-arm64@2.1.9
  - lefthook-freebsd-x64@2.1.9
  - lefthook-linux-arm64@2.1.9
  - lefthook-linux-x64@2.1.9
  - lefthook-openbsd-arm64@2.1.9
  - lefthook-openbsd-x64@2.1.9
  - lefthook-windows-arm64@2.1.9
  - lefthook-windows-x64@2.1.9
  - lefthook@2.1.9
